### ISSUE TITLE
Minor mistake in error message + feature request 

### ISSUE THREAD

**Issue by nelerey** [kravitsjacob/paxplot#15]
I encountered a mistaken error message when trying to do something that does not work in the first place. 

```python
paxfig = paxplot.pax_parallel(n_axes=len(scoredict.keys()))
print(len(scoredict.keys()) ) # 7

data = df_scores[["structure"] + list(scoredict.keys())].to_numpy()  
print(data.shape)  # (1566, 8), so len(data[0]) is 8

paxfig.plot(data)
print(len(paxfig.axes))  # 7
```

The error message resulting from this is:

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-26-f4ee5b26134c> in <module>
      5 data = df_scores[["structure"] + list(scoredict.keys())].to_numpy()
      6 
----> 7 paxfig.plot(data)
      8 
      9 paxfig.set_labels(list(scoredict.keys()))

~/.conda/envs/new-ada-env/lib/python3.8/site-packages/paxplot/core.py in wrapper(*args, **kwargs)
    709         original_flag_value = fig._show_unsafe_warning
    710         fig._show_unsafe_warning = False
--> 711         result = func(*args, **kwargs)
    712         fig._show_unsafe_warning = original_flag_value
    713         return result

~/.conda/envs/new-ada-env/lib/python3.8/site-packages/paxplot/core.py in plot(self, data)
    190             )
    191         **elif len(data[0]) > len(self.axes):
--> 192             raise ValueError(
    193                 'Supplied data has fewer columns than figure. Please recreate '
    194                 'paxfigure with appropriate n_axes'**

ValueError: Supplied data has fewer columns than figure. Please recreate paxfigure with appropriate n_axes
```

So either the elif test should be reversed, or the text should say "Supplied data has more columns than figure".

This is also a feature request: it would be convenient to be able to use one column, containing labels / categorical data (str) only for coloring, without having to also plot it on a separate axis and convert to numerical labels.

**Comment by kravitsjacob** [comment]
Hello,

Thank you for finding this. We appreciate your testing of paxplot as we work on an eventual full release. If you are interesting in contributing to correct the bug let me know. Otherwise, we will update the noted error message in the next beta release. 

As for the feature request, we can definitely look into getting something like that out in the next release. I believe it should be fairly simple. 

Also, not to convolute the thread, but this may be of interest to paxplot testers such as yourself. We are currently working on some significant speedups and refactoring of the paxplot backend (frontend interface will be the same), so be on the lookout for the new features when we get the release out!

Best,
Jacob

**Comment by kravitsjacob** [comment]
Error message fixed in https://github.com/kravitsjacob/paxplot/commit/83de8c64c486b4008827c5df8b2a29695ec99a65

Feature request forthcoming.

**Comment by kravitsjacob** [comment]
Feature request added in cacfe09da8a8b251719aed302d40ceed7d065269

Release coming soon!

**Comment by kravitsjacob** [comment]
Release is [here](https://github.com/kravitsjacob/paxplot/releases/tag/v0.1.2-beta). Thank you again for your suggestion!
